version: "3.3"
services:
  reverse-proxy:
    image: traefik:v2.10
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./reverse-proxy/traefik.yml:/traefik.yml:ro
      - ./reverse-proxy/letsencrypt:/letsencrypt
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=web-secure
      - traefik.http.routers.traefik.rule=Host(`taxi-krim82.ru`)
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=letsEncryptStaging
      - traefik.http.routers.traefik.service=api@internal
