version: "3.3"
services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data_db:/data/db
    env_file:
      - ./taxi-avrora/.env

  reverse-proxy:
    image: traefik:v2.10
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./reverse-proxy/traefik.yml:/traefik.yml:ro
      - ./reverse-proxy/letsencrypt:/letsencrypt
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=web-secure
      - traefik.http.routers.traefik.rule=Host(`traefik.taxi-krim82.ru`)
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=letsEncryptStaging
      - traefik.http.routers.traefik.service=api@internal

  taxi-avrora:
    depends_on:
      - db
    build:
      context: ./taxi-avrora
      dockerfile: Dockerfile
    restart: always
    working_dir: /app
    env_file:
      - ./taxi-avrora/.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.taxi-avrora.entrypoints=web-secure
      - traefik.http.routers.taxi-avrora.rule=Host(`taxi-avrora-krim.ru`)
      - traefik.http.routers.taxi-avrora.tls=true
      - traefik.http.routers.taxi-avrora.tls.certresolver=letsEncrypt
      - traefik.http.routers.taxi-avrora.service=taxi-avrora
      - traefik.http.services.taxi-avrora.loadbalancer.server.port=3100

  taxi-krim:
    build:
      context: ./taxi-krim
      dockerfile: Dockerfile
    restart: always
    working_dir: /app
    env_file:
      - ./taxi-krim/.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.taxi-krim.entrypoints=web-secure
      - traefik.http.routers.taxi-krim.rule=Host(`taxi-krim82.ru`) || Host(`taxi-krim.ru.com`)
      - traefik.http.routers.taxi-krim.tls=true
      - traefik.http.routers.taxi-krim.tls.certresolver=letsEncrypt
      - traefik.http.routers.taxi-krim.service=taxi-krim
      - traefik.http.services.taxi-krim.loadbalancer.server.port=3200

volumes:
  data_db:
