version: "3.3"
services:
  reverse-proxy:
    image: traefik:v2.10
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./reverse-proxy/traefik.yml:/traefik.yml:ro
      - ./reverse-proxy/letsencrypt:/letsencrypt
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=web-secure
      - traefik.http.routers.traefik.rule=Host(`traefik.taxi-krim82.ru`)
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=letsEncryptStaging
      - traefik.http.routers.traefik.service=api@internal

  taxi-avrora:
    build:
      context: ./taxi-avrora
      dockerfile: Dockerfile
    restart: always
    working_dir: /app
    environment:
      - PORT=3100
      - NODE_ENV="production"
      - SESSION_SECRET="BLA_BLA_BLA"
      - VK_CLIENT_ID=6447852
      - VK_CLIENT_SECRET="64D3T3CyifuXjwao3sHf"
      - VK_SERVICE_KEY=
        "7a04c2047a04c2047a04c204407a66a0e877a047a04c20420d577c17bed4f12bedd7916"
      - MAIL_PASSWORD="86r5bq53g7sM"
      - MONGODB_URL="mongodb://localhost/taxi-avrora"
      - TELEGRAM_NOTIFICATION_BOT_TOKEN=
        "6265759260:AAGxQ1ODoSxUqRYIes5u1Yo6PUrJ2Owk_RQ"
      - TELEGRAM_CHATS="460948825,290649024"
    labels:
      - traefik.enable=true
      - traefik.http.routers.taxi-avrora.entrypoints=web-secure
      - traefik.http.routers.taxi-avrora.rule=Host(`avrora.taxi-krim82.ru`)
      - traefik.http.routers.taxi-avrora.tls=true
      - traefik.http.routers.taxi-avrora.tls.certresolver=letsEncryptStaging
      - traefik.http.routers.taxi-avrora.service=taxi-avrora
      - traefik.http.services.taxi-avrora.loadbalancer.server.port=4173
