version: "3.3"
services:
  db:
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data_db:/data/db
      - ./db/backups:/backups
    env_file:
      - ./taxi-avrora/.env

  reverse-proxy:
    image: traefik:v2.10
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./reverse-proxy/traefik.dev.yml:/traefik.yml:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.rule=Host(`traefik.elena.localhost`)
      - traefik.http.routers.traefik.service=api@internal

  taxi-avrora:
    depends_on:
      - db
    build:
      context: ./taxi-avrora
      dockerfile: Dockerfile
    restart: always
    working_dir: /app
    env_file:
      - ./taxi-avrora/.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.taxi-avrora.entrypoints=web
      - traefik.http.routers.taxi-avrora.rule=Host(`avrora.elena.localhost`)
      - traefik.http.routers.taxi-avrora.service=taxi-avrora
      - traefik.http.services.taxi-avrora.loadbalancer.server.port=3100

  taxi-krim:
    build:
      context: ./taxi-krim
      dockerfile: Dockerfile
    restart: always
    working_dir: /app
    env_file:
      - ./taxi-krim/.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.taxi-krim.entrypoints=web
      - traefik.http.routers.taxi-krim.rule=Host(`krim.elena.localhost`)
      - traefik.http.routers.taxi-krim.service=taxi-krim
      - traefik.http.services.taxi-krim.loadbalancer.server.port=3200

  tuman-kalyan:
    image: nginx:1.23
    volumes:
      - ./tuman-kalyan/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./tuman-kalyan/www:/www:ro
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.tuman-kalyan.rule=Host(`kalyan.elena.localhost`)
      - traefik.http.routers.tuman-kalyan.entrypoints=web
      - traefik.http.services.tuman-kalyan.loadbalancer.server.port=80

volumes:
  data_db:
