name: Deploy to VPS

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  VK_CLIENT_ID: ${{ secrets.VK_CLIENT_ID }}
  VK_CLIENT_SECRET: ${{ secrets.VK_CLIENT_SECRET }}
  VK_SERVICE_KEY: ${{ secrets.VK_SERVICE_KEY }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 8.x
        uses: actions/setup-node@v2
        with:
          node-version: 8.x

      - name: Build
        run: |
          pm2 stop all
          npm ci
          npm run drop-cache
          npm run make

      - name: Start
        run: |
          npm start
          pm2 reload all
