version: "3.3"
services:
  db:
    image: mongo
    restart: always
    volumes:
      - data_db:/data/db
    env_file:
      - .env

  website:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 3000
    restart: always

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    hostname: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - website
    restart: always
    environment:
      - TZ=Europe/Moscow
      - LETSENCRYPT=true
      - LE_EMAIL=admin@taxi-avrora-krim.ru
      - LE_FQDN=taxi-avrora-krim.ru
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl

volumes:
  data_db:
